More graph, bootstrap components
FrederikRothe/BDSA-LitExplorer pull request #23
Opened 2021-11-29 14:38 UTC by NaddiNadja

2021-11-29 15:18 UTC, SebastianVFugmann approved these changes

2021-11-29 15:21 UTC, TheisHS commented on LitExplore/Client/Windows/TeamCustomisation.razor.css
> +    background-color: var(--ywllow);
ywlewoew

2021-11-29 15:22 UTC, TheisHS requested changes
der ryger en rigtig masse testkode ind i main, men indtil vi får backend på plads er det fair nok.

small fix, rest good

2021-11-29 15:50 UTC, TheisHS approved these changes
.d.)

2021-11-29 15:50 UTC, merged

2021-11-30 15:17 UTC, TheisHS commented on LitExplore/Client/wwwroot/js/bootstrap.bundle.js.map
> +{"version":3,"file":"bootstrap.bundle.js","sources":["../../js/src/util/index.js","../../js/src/dom/event-handler.js","../../js/src/dom/data.js","../../js/src/base-component.js","../../js/src/util/co
@NaddiNadja Why is this not ignored and downloaded through a cdn? 
![image](https://user-images.githubusercontent.com/74772370/144074518-f44c5aa7-a5ab-4f7c-b303-d4f6991e02c1.png)
Sincerely Emil Ø